sudo: true

services:
    - docker

dist: node:10-alpine

env:
    global:
    - IMAGE_NAME=webpage-test

language: node_js
node_js:
    - "10.16.3"

branches:
    only:
    - feature/webpagetest-docker

jobs:
    include:
      - stage: install
        script:
        - docker build -t ${IMAGE_NAME} .
        - chmod +x script.sh
      - stage: before deploy
        script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker images
        - docker tag $IMAGE_NAME $DOCKER_USERNAME/${IMAGE_NAME}
      - stage: test
        script:
        - ./script.sh $API_KEY $URL $USERNAME $PASS
      - stage: deploy
        script:
        - docker push $DOCKER_USERNAME/${IMAGE_NAME}