sudo: true

services:
    - docker

dist: node:10-alpine

env:
    global:
    - IMAGE_NAME=webpage-test

language: node_js
node_js:
    - "10.16.3"

branches:
    only:
    - feature/webpagetest-docker

jobs:
    include:
      - stage: install
        script:
        - chmod +x d_script.sh
        - docker build -t ${IMAGE_NAME} .
        - chmod +x script.sh
        - docker images
        - ./script.sh $API_KEY $URL $USERNAME $PASS