sudo: true

services:
	- docker

dist: node:10-alpine

env:
	global:
	- IMAGE_NAME=webpage-test

language: node_js
node_js:
	- "10.16.3"

install:
	- docker build -t ${IMAGE_NAME} .
	- chmod +x script.sh

before_deploy:
	- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
	- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"

deploy:
	provider: script
	script: docker push "${IMAGE_NAME}:latest"
	on:
		condition: ./script.sh $API_KEY $URL $USERNAME $PASS